image: ubuntu/22.10
sources:
- https://git.sr.ht/~tsileo/gemapi
packages:
- python3
- python3-dev
- python3.10-venv
tasks:
 - setup: |
    curl -sSL https://install.python-poetry.org | python3 -
 - tests: |
    export PATH="/home/build/.local/bin:$PATH"
    cd gemapi
    poetry install --no-interaction
    poetry run inv lint
    poetry run inv tests
